services:
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: edu-pulse
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_PORT: 3306
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
